export enum ApiErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  UNAUTHORIZED     = 'UNAUTHORIZED',
  TOKEN_EXPIRED    = 'TOKEN_EXPIRED',
  FORBIDDEN        = 'FORBIDDEN',
  NOT_FOUND        = 'NOT_FOUND',
  BOARD_NOT_FOUND  = 'BOARD_NOT_FOUND',
  COLUMN_NOT_FOUND = 'COLUMN_NOT_FOUND',
  CARD_NOT_FOUND   = 'CARD_NOT_FOUND',
  ALREADY_MEMBER   = 'ALREADY_MEMBER',
  INTERNAL_ERROR   = 'INTERNAL_ERROR',
}
